// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: paxos.proto
#ifndef GRPC_paxos_2eproto__INCLUDED
#define GRPC_paxos_2eproto__INCLUDED

#include "paxos.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class PaxosProposer final {
 public:
  static constexpr char const* service_full_name() {
    return "PaxosProposer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status client_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::ServerResponsePacket* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>> Asyncclient_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>>(Asyncclient_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>> PrepareAsyncclient_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>>(PrepareAsyncclient_requestRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>* Asyncclient_requestRaw(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ServerResponsePacket>* PrepareAsyncclient_requestRaw(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status client_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::ServerResponsePacket* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>> Asyncclient_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>>(Asyncclient_requestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>> PrepareAsyncclient_request(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>>(PrepareAsyncclient_requestRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void client_request(::grpc::ClientContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>* Asyncclient_requestRaw(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ServerResponsePacket>* PrepareAsyncclient_requestRaw(::grpc::ClientContext* context, const ::ClientRequestPacket& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_client_request_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status client_request(::grpc::ServerContext* context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_client_request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestclient_request(::grpc::ServerContext* context, ::ClientRequestPacket* request, ::grpc::ServerAsyncResponseWriter< ::ServerResponsePacket>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_client_request<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_client_request() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ClientRequestPacket, ::ServerResponsePacket>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ClientRequestPacket* request, ::ServerResponsePacket* response) { return this->client_request(context, request, response); }));}
    void SetMessageAllocatorFor_client_request(
        ::grpc::experimental::MessageAllocator< ::ClientRequestPacket, ::ServerResponsePacket>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ClientRequestPacket, ::ServerResponsePacket>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* client_request(
      ::grpc::CallbackServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* client_request(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_client_request<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_client_request<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_client_request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_client_request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestclient_request(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_client_request() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->client_request(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* client_request(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* client_request(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_client_request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_client_request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ClientRequestPacket, ::ServerResponsePacket>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ClientRequestPacket, ::ServerResponsePacket>* streamer) {
                       return this->Streamedclient_request(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_client_request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status client_request(::grpc::ServerContext* /*context*/, const ::ClientRequestPacket* /*request*/, ::ServerResponsePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedclient_request(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ClientRequestPacket,::ServerResponsePacket>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_client_request<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_client_request<Service > StreamedService;
};

class PaxosAccepter final {
 public:
  static constexpr char const* service_full_name() {
    return "PaxosAccepter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Prepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::PromisePacket* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>> AsyncPrepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>>(AsyncPrepareRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>> PrepareAsyncPrepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>>(PrepareAsyncPrepareRaw(context, request, cq));
    }
    virtual ::grpc::Status Propose(::grpc::ClientContext* context, const ::ProposePacket& request, ::AcceptPacket* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>> AsyncPropose(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>* AsyncPrepareRaw(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PromisePacket>* PrepareAsyncPrepareRaw(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>* AsyncProposeRaw(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AcceptPacket>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Prepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::PromisePacket* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromisePacket>> AsyncPrepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromisePacket>>(AsyncPrepareRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromisePacket>> PrepareAsyncPrepare(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PromisePacket>>(PrepareAsyncPrepareRaw(context, request, cq));
    }
    ::grpc::Status Propose(::grpc::ClientContext* context, const ::ProposePacket& request, ::AcceptPacket* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AcceptPacket>> AsyncPropose(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AcceptPacket>>(AsyncProposeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AcceptPacket>> PrepareAsyncPropose(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AcceptPacket>>(PrepareAsyncProposeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Prepare(::grpc::ClientContext* context, const ::PreparePacket* request, ::PromisePacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Propose(::grpc::ClientContext* context, const ::ProposePacket* request, ::AcceptPacket* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PromisePacket>* AsyncPrepareRaw(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PromisePacket>* PrepareAsyncPrepareRaw(::grpc::ClientContext* context, const ::PreparePacket& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AcceptPacket>* AsyncProposeRaw(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AcceptPacket>* PrepareAsyncProposeRaw(::grpc::ClientContext* context, const ::ProposePacket& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Prepare_;
    const ::grpc::internal::RpcMethod rpcmethod_Propose_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Prepare(::grpc::ServerContext* context, const ::PreparePacket* request, ::PromisePacket* response);
    virtual ::grpc::Status Propose(::grpc::ServerContext* context, const ::ProposePacket* request, ::AcceptPacket* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Prepare() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrepare(::grpc::ServerContext* context, ::PreparePacket* request, ::grpc::ServerAsyncResponseWriter< ::PromisePacket>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Propose() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::ProposePacket* request, ::grpc::ServerAsyncResponseWriter< ::AcceptPacket>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Prepare<WithAsyncMethod_Propose<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Prepare() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::PreparePacket, ::PromisePacket>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::PreparePacket* request, ::PromisePacket* response) { return this->Prepare(context, request, response); }));}
    void SetMessageAllocatorFor_Prepare(
        ::grpc::experimental::MessageAllocator< ::PreparePacket, ::PromisePacket>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::PreparePacket, ::PromisePacket>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Prepare(
      ::grpc::CallbackServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Prepare(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Propose() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ProposePacket, ::AcceptPacket>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ProposePacket* request, ::AcceptPacket* response) { return this->Propose(context, request, response); }));}
    void SetMessageAllocatorFor_Propose(
        ::grpc::experimental::MessageAllocator< ::ProposePacket, ::AcceptPacket>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ProposePacket, ::AcceptPacket>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Propose(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Prepare<ExperimentalWithCallbackMethod_Propose<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Prepare<ExperimentalWithCallbackMethod_Propose<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Prepare() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Propose() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Prepare() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrepare(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Propose() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPropose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Prepare() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Prepare(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Prepare(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Prepare(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Propose() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Propose(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Propose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Propose(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Prepare : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Prepare() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PreparePacket, ::PromisePacket>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::PreparePacket, ::PromisePacket>* streamer) {
                       return this->StreamedPrepare(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Prepare() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Prepare(::grpc::ServerContext* /*context*/, const ::PreparePacket* /*request*/, ::PromisePacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrepare(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PreparePacket,::PromisePacket>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Propose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Propose() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ProposePacket, ::AcceptPacket>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ProposePacket, ::AcceptPacket>* streamer) {
                       return this->StreamedPropose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Propose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Propose(::grpc::ServerContext* /*context*/, const ::ProposePacket* /*request*/, ::AcceptPacket* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPropose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ProposePacket,::AcceptPacket>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Prepare<WithStreamedUnaryMethod_Propose<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Prepare<WithStreamedUnaryMethod_Propose<Service > > StreamedService;
};


#endif  // GRPC_paxos_2eproto__INCLUDED
