// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sharedMemory.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sharedMemory_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sharedMemory_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sharedMemory_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sharedMemory_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sharedMemory_2eproto;
class QueryRequestPacket;
class QueryRequestPacketDefaultTypeInternal;
extern QueryRequestPacketDefaultTypeInternal _QueryRequestPacket_default_instance_;
class ReplyPacket;
class ReplyPacketDefaultTypeInternal;
extern ReplyPacketDefaultTypeInternal _ReplyPacket_default_instance_;
class UpdateRequestPacket;
class UpdateRequestPacketDefaultTypeInternal;
extern UpdateRequestPacketDefaultTypeInternal _UpdateRequestPacket_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::QueryRequestPacket* Arena::CreateMaybeMessage<::QueryRequestPacket>(Arena*);
template<> ::ReplyPacket* Arena::CreateMaybeMessage<::ReplyPacket>(Arena*);
template<> ::UpdateRequestPacket* Arena::CreateMaybeMessage<::UpdateRequestPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class QueryRequestPacket PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QueryRequestPacket) */ {
 public:
  inline QueryRequestPacket() : QueryRequestPacket(nullptr) {}
  virtual ~QueryRequestPacket();

  QueryRequestPacket(const QueryRequestPacket& from);
  QueryRequestPacket(QueryRequestPacket&& from) noexcept
    : QueryRequestPacket() {
    *this = ::std::move(from);
  }

  inline QueryRequestPacket& operator=(const QueryRequestPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryRequestPacket& operator=(QueryRequestPacket&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const QueryRequestPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QueryRequestPacket* internal_default_instance() {
    return reinterpret_cast<const QueryRequestPacket*>(
               &_QueryRequestPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QueryRequestPacket& a, QueryRequestPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryRequestPacket* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryRequestPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QueryRequestPacket* New() const final {
    return CreateMaybeMessage<QueryRequestPacket>(nullptr);
  }

  QueryRequestPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QueryRequestPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const QueryRequestPacket& from);
  void MergeFrom(const QueryRequestPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryRequestPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QueryRequestPacket";
  }
  protected:
  explicit QueryRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharedMemory_2eproto);
    return ::descriptor_table_sharedMemory_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kClientIDFieldNumber = 1,
  };
  // string key = 2;
  void clear_key();
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // int32 clientID = 1;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:QueryRequestPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharedMemory_2eproto;
};
// -------------------------------------------------------------------

class UpdateRequestPacket PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UpdateRequestPacket) */ {
 public:
  inline UpdateRequestPacket() : UpdateRequestPacket(nullptr) {}
  virtual ~UpdateRequestPacket();

  UpdateRequestPacket(const UpdateRequestPacket& from);
  UpdateRequestPacket(UpdateRequestPacket&& from) noexcept
    : UpdateRequestPacket() {
    *this = ::std::move(from);
  }

  inline UpdateRequestPacket& operator=(const UpdateRequestPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateRequestPacket& operator=(UpdateRequestPacket&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdateRequestPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateRequestPacket* internal_default_instance() {
    return reinterpret_cast<const UpdateRequestPacket*>(
               &_UpdateRequestPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(UpdateRequestPacket& a, UpdateRequestPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateRequestPacket* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateRequestPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdateRequestPacket* New() const final {
    return CreateMaybeMessage<UpdateRequestPacket>(nullptr);
  }

  UpdateRequestPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdateRequestPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdateRequestPacket& from);
  void MergeFrom(const UpdateRequestPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateRequestPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UpdateRequestPacket";
  }
  protected:
  explicit UpdateRequestPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharedMemory_2eproto);
    return ::descriptor_table_sharedMemory_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kValueFieldNumber = 3,
    kClientIDFieldNumber = 1,
    kLtFieldNumber = 4,
    kFromClientFieldNumber = 5,
  };
  // string key = 2;
  void clear_key();
  const std::string& key() const;
  void set_key(const std::string& value);
  void set_key(std::string&& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  std::string* mutable_key();
  std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string value = 3;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // int32 clientID = 1;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 lt = 4;
  void clear_lt();
  ::PROTOBUF_NAMESPACE_ID::int32 lt() const;
  void set_lt(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lt() const;
  void _internal_set_lt(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 fromClient = 5;
  void clear_fromclient();
  ::PROTOBUF_NAMESPACE_ID::int32 fromclient() const;
  void set_fromclient(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_fromclient() const;
  void _internal_set_fromclient(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:UpdateRequestPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  ::PROTOBUF_NAMESPACE_ID::int32 lt_;
  ::PROTOBUF_NAMESPACE_ID::int32 fromclient_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharedMemory_2eproto;
};
// -------------------------------------------------------------------

class ReplyPacket PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ReplyPacket) */ {
 public:
  inline ReplyPacket() : ReplyPacket(nullptr) {}
  virtual ~ReplyPacket();

  ReplyPacket(const ReplyPacket& from);
  ReplyPacket(ReplyPacket&& from) noexcept
    : ReplyPacket() {
    *this = ::std::move(from);
  }

  inline ReplyPacket& operator=(const ReplyPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReplyPacket& operator=(ReplyPacket&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReplyPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReplyPacket* internal_default_instance() {
    return reinterpret_cast<const ReplyPacket*>(
               &_ReplyPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReplyPacket& a, ReplyPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(ReplyPacket* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReplyPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReplyPacket* New() const final {
    return CreateMaybeMessage<ReplyPacket>(nullptr);
  }

  ReplyPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReplyPacket>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReplyPacket& from);
  void MergeFrom(const ReplyPacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReplyPacket* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ReplyPacket";
  }
  protected:
  explicit ReplyPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sharedMemory_2eproto);
    return ::descriptor_table_sharedMemory_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 4,
    kServerIDFieldNumber = 1,
    kLtFieldNumber = 2,
    kClientIDFieldNumber = 3,
    kIsSuccessFieldNumber = 5,
  };
  // string value = 4;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // int32 serverID = 1;
  void clear_serverid();
  ::PROTOBUF_NAMESPACE_ID::int32 serverid() const;
  void set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_serverid() const;
  void _internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 lt = 2;
  void clear_lt();
  ::PROTOBUF_NAMESPACE_ID::int32 lt() const;
  void set_lt(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lt() const;
  void _internal_set_lt(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 clientID = 3;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool is_success = 5;
  void clear_is_success();
  bool is_success() const;
  void set_is_success(bool value);
  private:
  bool _internal_is_success() const;
  void _internal_set_is_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ReplyPacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::int32 serverid_;
  ::PROTOBUF_NAMESPACE_ID::int32 lt_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  bool is_success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sharedMemory_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QueryRequestPacket

// int32 clientID = 1;
inline void QueryRequestPacket::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 QueryRequestPacket::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 QueryRequestPacket::clientid() const {
  // @@protoc_insertion_point(field_get:QueryRequestPacket.clientID)
  return _internal_clientid();
}
inline void QueryRequestPacket::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void QueryRequestPacket::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:QueryRequestPacket.clientID)
}

// string key = 2;
inline void QueryRequestPacket::clear_key() {
  key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& QueryRequestPacket::key() const {
  // @@protoc_insertion_point(field_get:QueryRequestPacket.key)
  return _internal_key();
}
inline void QueryRequestPacket::set_key(const std::string& value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:QueryRequestPacket.key)
}
inline std::string* QueryRequestPacket::mutable_key() {
  // @@protoc_insertion_point(field_mutable:QueryRequestPacket.key)
  return _internal_mutable_key();
}
inline const std::string& QueryRequestPacket::_internal_key() const {
  return key_.Get();
}
inline void QueryRequestPacket::_internal_set_key(const std::string& value) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void QueryRequestPacket::set_key(std::string&& value) {
  
  key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:QueryRequestPacket.key)
}
inline void QueryRequestPacket::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:QueryRequestPacket.key)
}
inline void QueryRequestPacket::set_key(const char* value,
    size_t size) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:QueryRequestPacket.key)
}
inline std::string* QueryRequestPacket::_internal_mutable_key() {
  
  return key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* QueryRequestPacket::release_key() {
  // @@protoc_insertion_point(field_release:QueryRequestPacket.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void QueryRequestPacket::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:QueryRequestPacket.key)
}

// -------------------------------------------------------------------

// UpdateRequestPacket

// int32 clientID = 1;
inline void UpdateRequestPacket::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::clientid() const {
  // @@protoc_insertion_point(field_get:UpdateRequestPacket.clientID)
  return _internal_clientid();
}
inline void UpdateRequestPacket::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void UpdateRequestPacket::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:UpdateRequestPacket.clientID)
}

// string key = 2;
inline void UpdateRequestPacket::clear_key() {
  key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UpdateRequestPacket::key() const {
  // @@protoc_insertion_point(field_get:UpdateRequestPacket.key)
  return _internal_key();
}
inline void UpdateRequestPacket::set_key(const std::string& value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:UpdateRequestPacket.key)
}
inline std::string* UpdateRequestPacket::mutable_key() {
  // @@protoc_insertion_point(field_mutable:UpdateRequestPacket.key)
  return _internal_mutable_key();
}
inline const std::string& UpdateRequestPacket::_internal_key() const {
  return key_.Get();
}
inline void UpdateRequestPacket::_internal_set_key(const std::string& value) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UpdateRequestPacket::set_key(std::string&& value) {
  
  key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:UpdateRequestPacket.key)
}
inline void UpdateRequestPacket::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:UpdateRequestPacket.key)
}
inline void UpdateRequestPacket::set_key(const char* value,
    size_t size) {
  
  key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:UpdateRequestPacket.key)
}
inline std::string* UpdateRequestPacket::_internal_mutable_key() {
  
  return key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UpdateRequestPacket::release_key() {
  // @@protoc_insertion_point(field_release:UpdateRequestPacket.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UpdateRequestPacket::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:UpdateRequestPacket.key)
}

// string value = 3;
inline void UpdateRequestPacket::clear_value() {
  value_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& UpdateRequestPacket::value() const {
  // @@protoc_insertion_point(field_get:UpdateRequestPacket.value)
  return _internal_value();
}
inline void UpdateRequestPacket::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:UpdateRequestPacket.value)
}
inline std::string* UpdateRequestPacket::mutable_value() {
  // @@protoc_insertion_point(field_mutable:UpdateRequestPacket.value)
  return _internal_mutable_value();
}
inline const std::string& UpdateRequestPacket::_internal_value() const {
  return value_.Get();
}
inline void UpdateRequestPacket::_internal_set_value(const std::string& value) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UpdateRequestPacket::set_value(std::string&& value) {
  
  value_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:UpdateRequestPacket.value)
}
inline void UpdateRequestPacket::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:UpdateRequestPacket.value)
}
inline void UpdateRequestPacket::set_value(const char* value,
    size_t size) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:UpdateRequestPacket.value)
}
inline std::string* UpdateRequestPacket::_internal_mutable_value() {
  
  return value_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UpdateRequestPacket::release_value() {
  // @@protoc_insertion_point(field_release:UpdateRequestPacket.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UpdateRequestPacket::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:UpdateRequestPacket.value)
}

// int32 lt = 4;
inline void UpdateRequestPacket::clear_lt() {
  lt_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::_internal_lt() const {
  return lt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::lt() const {
  // @@protoc_insertion_point(field_get:UpdateRequestPacket.lt)
  return _internal_lt();
}
inline void UpdateRequestPacket::_internal_set_lt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lt_ = value;
}
inline void UpdateRequestPacket::set_lt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lt(value);
  // @@protoc_insertion_point(field_set:UpdateRequestPacket.lt)
}

// int32 fromClient = 5;
inline void UpdateRequestPacket::clear_fromclient() {
  fromclient_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::_internal_fromclient() const {
  return fromclient_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 UpdateRequestPacket::fromclient() const {
  // @@protoc_insertion_point(field_get:UpdateRequestPacket.fromClient)
  return _internal_fromclient();
}
inline void UpdateRequestPacket::_internal_set_fromclient(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  fromclient_ = value;
}
inline void UpdateRequestPacket::set_fromclient(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_fromclient(value);
  // @@protoc_insertion_point(field_set:UpdateRequestPacket.fromClient)
}

// -------------------------------------------------------------------

// ReplyPacket

// int32 serverID = 1;
inline void ReplyPacket::clear_serverid() {
  serverid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::_internal_serverid() const {
  return serverid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::serverid() const {
  // @@protoc_insertion_point(field_get:ReplyPacket.serverID)
  return _internal_serverid();
}
inline void ReplyPacket::_internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  serverid_ = value;
}
inline void ReplyPacket::set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:ReplyPacket.serverID)
}

// int32 lt = 2;
inline void ReplyPacket::clear_lt() {
  lt_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::_internal_lt() const {
  return lt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::lt() const {
  // @@protoc_insertion_point(field_get:ReplyPacket.lt)
  return _internal_lt();
}
inline void ReplyPacket::_internal_set_lt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lt_ = value;
}
inline void ReplyPacket::set_lt(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lt(value);
  // @@protoc_insertion_point(field_set:ReplyPacket.lt)
}

// int32 clientID = 3;
inline void ReplyPacket::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReplyPacket::clientid() const {
  // @@protoc_insertion_point(field_get:ReplyPacket.clientID)
  return _internal_clientid();
}
inline void ReplyPacket::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void ReplyPacket::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:ReplyPacket.clientID)
}

// string value = 4;
inline void ReplyPacket::clear_value() {
  value_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ReplyPacket::value() const {
  // @@protoc_insertion_point(field_get:ReplyPacket.value)
  return _internal_value();
}
inline void ReplyPacket::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:ReplyPacket.value)
}
inline std::string* ReplyPacket::mutable_value() {
  // @@protoc_insertion_point(field_mutable:ReplyPacket.value)
  return _internal_mutable_value();
}
inline const std::string& ReplyPacket::_internal_value() const {
  return value_.Get();
}
inline void ReplyPacket::_internal_set_value(const std::string& value) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ReplyPacket::set_value(std::string&& value) {
  
  value_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ReplyPacket.value)
}
inline void ReplyPacket::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ReplyPacket.value)
}
inline void ReplyPacket::set_value(const char* value,
    size_t size) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ReplyPacket.value)
}
inline std::string* ReplyPacket::_internal_mutable_value() {
  
  return value_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ReplyPacket::release_value() {
  // @@protoc_insertion_point(field_release:ReplyPacket.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReplyPacket::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ReplyPacket.value)
}

// bool is_success = 5;
inline void ReplyPacket::clear_is_success() {
  is_success_ = false;
}
inline bool ReplyPacket::_internal_is_success() const {
  return is_success_;
}
inline bool ReplyPacket::is_success() const {
  // @@protoc_insertion_point(field_get:ReplyPacket.is_success)
  return _internal_is_success();
}
inline void ReplyPacket::_internal_set_is_success(bool value) {
  
  is_success_ = value;
}
inline void ReplyPacket::set_is_success(bool value) {
  _internal_set_is_success(value);
  // @@protoc_insertion_point(field_set:ReplyPacket.is_success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sharedMemory_2eproto
